<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BobotcplsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('bobotcpls')->delete();

        \DB::table('bobotcpls')->insert([
            0 => [
                'id' => 1,
                'tahun_ajaran_id' => 1,
                'mata_kuliah_id' => 1,
                'cpl_id' => 1,
                'cpmk_id' => 1,
                'btp_id' => 1,
                'semester' => '1',
                'bobot_cpl' => 20.0,
                'created_at' => '2021-09-25 10:02:20',
                'updated_at' => '2021-09-25 10:02:20',
            ],
            1 => [
                'id' => 2,
                'tahun_ajaran_id' => 2,
                'mata_kuliah_id' => 2,
                'cpl_id' => 2,
                'cpmk_id' => 2,
                'btp_id' => 2,
                'semester' => '2',
                'bobot_cpl' => 30.0,
                'created_at' => '2021-09-25 10:02:20',
                'updated_at' => '2021-09-25 10:02:20',
            ],
            2 => [
                'id' => 3,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 3,
                'cpmk_id' => 3,
                'btp_id' => 3,
                'semester' => '1',
                'bobot_cpl' => 10.0,
                'created_at' => '2021-09-25 15:29:49',
                'updated_at' => '2021-09-25 15:29:49',
            ],
            3 => [
                'id' => 4,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 3,
                'cpmk_id' => 12,
                'btp_id' => 11,
                'semester' => '1',
                'bobot_cpl' => 10.0,
                'created_at' => '2021-09-25 15:30:14',
                'updated_at' => '2021-09-25 15:30:14',
            ],
            4 => [
                'id' => 5,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 4,
                'btp_id' => 4,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:30:31',
                'updated_at' => '2021-09-25 15:33:44',
            ],
            5 => [
                'id' => 6,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 6,
                'btp_id' => 5,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:35:20',
                'updated_at' => '2021-09-25 15:35:20',
            ],
            6 => [
                'id' => 7,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 7,
                'btp_id' => 6,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:35:33',
                'updated_at' => '2021-09-25 15:35:33',
            ],
            7 => [
                'id' => 8,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 8,
                'btp_id' => 7,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:35:54',
                'updated_at' => '2021-09-25 15:35:54',
            ],
            8 => [
                'id' => 9,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 9,
                'btp_id' => 8,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:36:16',
                'updated_at' => '2021-09-25 15:36:16',
            ],
            9 => [
                'id' => 10,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 13,
                'btp_id' => 12,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:36:25',
                'updated_at' => '2021-09-25 15:36:25',
            ],
            10 => [
                'id' => 11,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 10,
                'btp_id' => 9,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:36:36',
                'updated_at' => '2021-09-25 15:36:36',
            ],
            11 => [
                'id' => 12,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 11,
                'btp_id' => 10,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:36:54',
                'updated_at' => '2021-09-25 15:36:54',
            ],
            12 => [
                'id' => 13,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 4,
                'cpmk_id' => 12,
                'btp_id' => 11,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:37:10',
                'updated_at' => '2021-09-25 15:37:10',
            ],
            13 => [
                'id' => 14,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 4,
                'btp_id' => 4,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:37:43',
                'updated_at' => '2021-09-25 15:38:00',
            ],
            14 => [
                'id' => 15,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 6,
                'btp_id' => 5,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:38:39',
                'updated_at' => '2021-09-25 15:38:39',
            ],
            15 => [
                'id' => 16,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 7,
                'btp_id' => 6,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:38:46',
                'updated_at' => '2021-09-25 15:38:46',
            ],
            16 => [
                'id' => 17,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 8,
                'btp_id' => 7,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:39:04',
                'updated_at' => '2021-09-25 15:39:04',
            ],
            17 => [
                'id' => 18,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 9,
                'btp_id' => 8,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:39:12',
                'updated_at' => '2021-09-25 15:39:12',
            ],
            18 => [
                'id' => 19,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 10,
                'btp_id' => 9,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:39:17',
                'updated_at' => '2021-09-25 15:39:17',
            ],
            19 => [
                'id' => 20,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 11,
                'btp_id' => 10,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:39:39',
                'updated_at' => '2021-09-25 15:39:39',
            ],
            20 => [
                'id' => 21,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 12,
                'btp_id' => 11,
                'semester' => '1',
                'bobot_cpl' => 4.44,
                'created_at' => '2021-09-25 15:39:54',
                'updated_at' => '2021-09-25 15:39:54',
            ],
            21 => [
                'id' => 22,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpl_id' => 6,
                'cpmk_id' => 13,
                'btp_id' => 12,
                'semester' => '1',
                'bobot_cpl' => 4.52,
                'created_at' => '2021-09-25 15:40:44',
                'updated_at' => '2021-09-25 15:42:20',
            ],
        ]);
    }
}
