<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BtpsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('btps')->delete();

        \DB::table('btps')->insert([
            0 => [
                'id' => 1,
                'tahun_ajaran_id' => 1,
                'mata_kuliah_id' => 1,
                'cpmk_id' => 1,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 1',
                'semester' => '1',
                'kategori' => 1,
                'bobot' => 20.0,
                'created_at' => '2021-09-25 10:02:20',
                'updated_at' => '2021-09-25 10:02:20',
            ],
            1 => [
                'id' => 2,
                'tahun_ajaran_id' => 2,
                'mata_kuliah_id' => 2,
                'cpmk_id' => 2,
                'dosen_admin_id' => 2,
                'nama' => 'UTS',
                'semester' => '2',
                'kategori' => 1,
                'bobot' => 30.0,
                'created_at' => '2021-09-25 10:02:20',
                'updated_at' => '2021-09-25 10:02:20',
            ],
            2 => [
                'id' => 3,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 3,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 1a',
                'semester' => '1',
                'kategori' => 1,
                'bobot' => 2.5,
                'created_at' => '2021-09-25 15:17:47',
                'updated_at' => '2021-09-25 15:18:12',
            ],
            3 => [
                'id' => 4,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 4,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 1b',
                'semester' => '1',
                'kategori' => 1,
                'bobot' => 2.5,
                'created_at' => '2021-09-25 15:18:07',
                'updated_at' => '2021-09-25 15:34:54',
            ],
            4 => [
                'id' => 5,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 6,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 2a',
                'semester' => '1',
                'kategori' => 1,
                'bobot' => 5.0,
                'created_at' => '2021-09-25 15:21:07',
                'updated_at' => '2021-09-25 15:21:07',
            ],
            5 => [
                'id' => 6,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 7,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 2b',
                'semester' => '1',
                'kategori' => 1,
                'bobot' => 5.0,
                'created_at' => '2021-09-25 15:21:19',
                'updated_at' => '2021-09-25 15:21:19',
            ],
            6 => [
                'id' => 7,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 8,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 2c',
                'semester' => '1',
                'kategori' => 1,
                'bobot' => 5.0,
                'created_at' => '2021-09-25 15:21:50',
                'updated_at' => '2021-09-25 15:21:50',
            ],
            7 => [
                'id' => 8,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 9,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 3',
                'semester' => '1',
                'kategori' => 2,
                'bobot' => 10.0,
                'created_at' => '2021-09-25 15:22:14',
                'updated_at' => '2021-09-25 15:22:14',
            ],
            8 => [
                'id' => 9,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 10,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 4a',
                'semester' => '1',
                'kategori' => 2,
                'bobot' => 15.0,
                'created_at' => '2021-09-25 15:22:42',
                'updated_at' => '2021-09-25 15:22:42',
            ],
            9 => [
                'id' => 10,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 11,
                'dosen_admin_id' => 1,
                'nama' => 'Tugas 4b',
                'semester' => '1',
                'kategori' => 2,
                'bobot' => 5.0,
                'created_at' => '2021-09-25 15:23:06',
                'updated_at' => '2021-09-25 15:23:06',
            ],
            10 => [
                'id' => 11,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 12,
                'dosen_admin_id' => 2,
                'nama' => 'Tugas 5',
                'semester' => '1',
                'kategori' => 3,
                'bobot' => 30.0,
                'created_at' => '2021-09-25 15:24:22',
                'updated_at' => '2021-09-26 04:51:16',
            ],
            11 => [
                'id' => 12,
                'tahun_ajaran_id' => 3,
                'mata_kuliah_id' => 3,
                'cpmk_id' => 13,
                'dosen_admin_id' => 2,
                'nama' => 'Tugas 6',
                'semester' => '1',
                'kategori' => 3,
                'bobot' => 20.0,
                'created_at' => '2021-09-25 15:24:45',
                'updated_at' => '2021-09-26 04:51:20',
            ],
        ]);
    }
}
